// Generated by gencpp from file assignment1/NewPositionResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_MESSAGE_NEWPOSITIONRESPONSE_H
#define ASSIGNMENT1_MESSAGE_NEWPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment1
{
template <class ContainerAllocator>
struct NewPositionResponse_
{
  typedef NewPositionResponse_<ContainerAllocator> Type;

  NewPositionResponse_()
    : xnew(0.0)
    , ynew(0.0)
    , znew(0.0)  {
    }
  NewPositionResponse_(const ContainerAllocator& _alloc)
    : xnew(0.0)
    , ynew(0.0)
    , znew(0.0)  {
  (void)_alloc;
    }



   typedef double _xnew_type;
  _xnew_type xnew;

   typedef double _ynew_type;
  _ynew_type ynew;

   typedef double _znew_type;
  _znew_type znew;





  typedef boost::shared_ptr< ::assignment1::NewPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment1::NewPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NewPositionResponse_

typedef ::assignment1::NewPositionResponse_<std::allocator<void> > NewPositionResponse;

typedef boost::shared_ptr< ::assignment1::NewPositionResponse > NewPositionResponsePtr;
typedef boost::shared_ptr< ::assignment1::NewPositionResponse const> NewPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment1::NewPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment1::NewPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment1::NewPositionResponse_<ContainerAllocator1> & lhs, const ::assignment1::NewPositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.xnew == rhs.xnew &&
    lhs.ynew == rhs.ynew &&
    lhs.znew == rhs.znew;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment1::NewPositionResponse_<ContainerAllocator1> & lhs, const ::assignment1::NewPositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment1::NewPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::NewPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::NewPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::NewPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::NewPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::NewPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment1::NewPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68545952d6a542e06cf4f426fbd45143";
  }

  static const char* value(const ::assignment1::NewPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68545952d6a542e0ULL;
  static const uint64_t static_value2 = 0x6cf4f426fbd45143ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment1::NewPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment1/NewPositionResponse";
  }

  static const char* value(const ::assignment1::NewPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment1::NewPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 xnew\n"
"float64 ynew\n"
"float64 znew\n"
;
  }

  static const char* value(const ::assignment1::NewPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment1::NewPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xnew);
      stream.next(m.ynew);
      stream.next(m.znew);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NewPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment1::NewPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment1::NewPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "xnew: ";
    Printer<double>::stream(s, indent + "  ", v.xnew);
    s << indent << "ynew: ";
    Printer<double>::stream(s, indent + "  ", v.ynew);
    s << indent << "znew: ";
    Printer<double>::stream(s, indent + "  ", v.znew);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT1_MESSAGE_NEWPOSITIONRESPONSE_H
