// Generated by gencpp from file assignment1/NewPosition.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_MESSAGE_NEWPOSITION_H
#define ASSIGNMENT1_MESSAGE_NEWPOSITION_H

#include <ros/service_traits.h>


#include <assignment1/NewPositionRequest.h>
#include <assignment1/NewPositionResponse.h>


namespace assignment1
{

struct NewPosition
{

typedef NewPositionRequest Request;
typedef NewPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NewPosition
} // namespace assignment1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment1::NewPosition > {
  static const char* value()
  {
    return "c122c247df04a12a46d905c9d7c5946b";
  }

  static const char* value(const ::assignment1::NewPosition&) { return value(); }
};

template<>
struct DataType< ::assignment1::NewPosition > {
  static const char* value()
  {
    return "assignment1/NewPosition";
  }

  static const char* value(const ::assignment1::NewPosition&) { return value(); }
};


// service_traits::MD5Sum< ::assignment1::NewPositionRequest> should match
// service_traits::MD5Sum< ::assignment1::NewPosition >
template<>
struct MD5Sum< ::assignment1::NewPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment1::NewPosition >::value();
  }
  static const char* value(const ::assignment1::NewPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment1::NewPositionRequest> should match
// service_traits::DataType< ::assignment1::NewPosition >
template<>
struct DataType< ::assignment1::NewPositionRequest>
{
  static const char* value()
  {
    return DataType< ::assignment1::NewPosition >::value();
  }
  static const char* value(const ::assignment1::NewPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment1::NewPositionResponse> should match
// service_traits::MD5Sum< ::assignment1::NewPosition >
template<>
struct MD5Sum< ::assignment1::NewPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment1::NewPosition >::value();
  }
  static const char* value(const ::assignment1::NewPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment1::NewPositionResponse> should match
// service_traits::DataType< ::assignment1::NewPosition >
template<>
struct DataType< ::assignment1::NewPositionResponse>
{
  static const char* value()
  {
    return DataType< ::assignment1::NewPosition >::value();
  }
  static const char* value(const ::assignment1::NewPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT1_MESSAGE_NEWPOSITION_H
