// Generated by gencpp from file question4/JointPositionRequest.msg
// DO NOT EDIT!


#ifndef QUESTION4_MESSAGE_JOINTPOSITIONREQUEST_H
#define QUESTION4_MESSAGE_JOINTPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace question4
{
template <class ContainerAllocator>
struct JointPositionRequest_
{
  typedef JointPositionRequest_<ContainerAllocator> Type;

  JointPositionRequest_()
    : first(0.0)
    , second(0.0)
    , third(0.0)
    , fourth(0.0)  {
    }
  JointPositionRequest_(const ContainerAllocator& _alloc)
    : first(0.0)
    , second(0.0)
    , third(0.0)
    , fourth(0.0)  {
  (void)_alloc;
    }



   typedef double _first_type;
  _first_type first;

   typedef double _second_type;
  _second_type second;

   typedef double _third_type;
  _third_type third;

   typedef double _fourth_type;
  _fourth_type fourth;





  typedef boost::shared_ptr< ::question4::JointPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::question4::JointPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct JointPositionRequest_

typedef ::question4::JointPositionRequest_<std::allocator<void> > JointPositionRequest;

typedef boost::shared_ptr< ::question4::JointPositionRequest > JointPositionRequestPtr;
typedef boost::shared_ptr< ::question4::JointPositionRequest const> JointPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::question4::JointPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::question4::JointPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::question4::JointPositionRequest_<ContainerAllocator1> & lhs, const ::question4::JointPositionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.first == rhs.first &&
    lhs.second == rhs.second &&
    lhs.third == rhs.third &&
    lhs.fourth == rhs.fourth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::question4::JointPositionRequest_<ContainerAllocator1> & lhs, const ::question4::JointPositionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace question4

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::question4::JointPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::question4::JointPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::question4::JointPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::question4::JointPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::question4::JointPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::question4::JointPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::question4::JointPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a535115e63a8d55f9b2d3b373b8ddaa";
  }

  static const char* value(const ::question4::JointPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a535115e63a8d55ULL;
  static const uint64_t static_value2 = 0xf9b2d3b373b8ddaaULL;
};

template<class ContainerAllocator>
struct DataType< ::question4::JointPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "question4/JointPositionRequest";
  }

  static const char* value(const ::question4::JointPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::question4::JointPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 first\n"
"float64 second\n"
"float64 third\n"
"float64 fourth\n"
;
  }

  static const char* value(const ::question4::JointPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::question4::JointPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.first);
      stream.next(m.second);
      stream.next(m.third);
      stream.next(m.fourth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::question4::JointPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::question4::JointPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "first: ";
    Printer<double>::stream(s, indent + "  ", v.first);
    s << indent << "second: ";
    Printer<double>::stream(s, indent + "  ", v.second);
    s << indent << "third: ";
    Printer<double>::stream(s, indent + "  ", v.third);
    s << indent << "fourth: ";
    Printer<double>::stream(s, indent + "  ", v.fourth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUESTION4_MESSAGE_JOINTPOSITIONREQUEST_H
