// Generated by gencpp from file question4/JointPositionResponse.msg
// DO NOT EDIT!


#ifndef QUESTION4_MESSAGE_JOINTPOSITIONRESPONSE_H
#define QUESTION4_MESSAGE_JOINTPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace question4
{
template <class ContainerAllocator>
struct JointPositionResponse_
{
  typedef JointPositionResponse_<ContainerAllocator> Type;

  JointPositionResponse_()
    {
    }
  JointPositionResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::question4::JointPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::question4::JointPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct JointPositionResponse_

typedef ::question4::JointPositionResponse_<std::allocator<void> > JointPositionResponse;

typedef boost::shared_ptr< ::question4::JointPositionResponse > JointPositionResponsePtr;
typedef boost::shared_ptr< ::question4::JointPositionResponse const> JointPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::question4::JointPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::question4::JointPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace question4

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::question4::JointPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::question4::JointPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::question4::JointPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::question4::JointPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::question4::JointPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::question4::JointPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::question4::JointPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::question4::JointPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::question4::JointPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "question4/JointPositionResponse";
  }

  static const char* value(const ::question4::JointPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::question4::JointPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::question4::JointPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::question4::JointPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::question4::JointPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::question4::JointPositionResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // QUESTION4_MESSAGE_JOINTPOSITIONRESPONSE_H
